In [7]:
# 패키지 설치

!pip install pyyaml requests

Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)

# 1. 접근토큰 발급

In [8]:
import yaml
import os

# 파일 경로 설정
config_path = '/content/config.yaml'

# 파일 존재 여부 확인 후 불러오기
if os.path.exists(config_path):
    with open(config_path, 'r') as f:
        config = yaml.load(f, Loader=yaml.FullLoader)

    api_key = config['hantu']['api_key']
    secret_key = config['hantu']['secret_key']
    print(f"API Key loaded successfully: {api_key[:5]}...")
else:
    print(f"오류: {config_path} 파일을 찾을 수 없습니다. 파일이 정확한 위치에 업로드되었는지 확인해주세요.")

API Key loaded successfully: PSier...

In [9]:
import requests
import json

base_url = 'https://openapivts.koreainvestment.com:29443'

headers = {"content-type":"application/json"}
body = {
        "grant_type":"client_credentials",
        "appkey":api_key,
        "appsecret":secret_key,
        }
url = base_url + '/oauth2/tokenP'
res = requests.post(url, headers=headers, data=json.dumps(body)).json()
res

{'access_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImQxYWI0MTdjLWU2NWEtNDg0NC1hNDY3LWM4MmU2N2QyZWRiYyIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc4MzA2MDU0OCwiaWF0IjoxNzgyOTc0MTQ4LCJqdGkiOiJQU2llckpNc3pWTkZSMVhabGwwZTJkd1FnZzltTDNGZU9LREcifQ.pmW0ZJTu4MHHUj3LlEMNDBTNPc0URIki3o5VSIaOiOA3KaB5Qrxh6_S2OjROYJUdsMQeJzQeHZ-ToqbMtI-tXg',
 'access_token_token_expired': '2026-07-03 15:35:48',
 'token_type': 'Bearer',
 'expires_in': 86400}

#### 접근토큰 설명

- access_token: 발급받은 접근토큰. 이 값을 저장해두고 사용하면 됨
- access_token_token_expired: 접근토큰 만기시점. 발급 순간부터 24시간 후
- token_type: 접근토큰유형. 'Bearer' 값이 들어옴
- expires_in: 만기까지 남은 시간(초)

#주가 데이터 가져오기

In [10]:
access_token = res['access_token']

In [11]:
ticker = '005930'

tr_id = 'FHKST01010100'

headers = {"content-type":"application/json",
                "appkey":api_key,
                "appsecret":secret_key,
                "authorization":f"Bearer {access_token}",
                "tr_id":tr_id,
                }

params = {
        "fid_cond_mrkt_div_code":"J",
        "fid_input_iscd": ticker
        }
url = base_url + '/uapi/domestic-stock/v1/quotations/inquire-price'

response = requests.get(url, headers=headers, params=params)

In [12]:
response

In [13]:
data = response.json()
data

{'output': {'iscd_stat_cls_code': '55',
  'marg_rate': '60.00',
  'rprs_mrkt_kor_name': 'KOSPI200',
  'bstp_kor_isnm': '전기·전자',
  'temp_stop_yn': 'N',
  'oprc_rang_cont_yn': 'N',
  'clpr_rang_cont_yn': 'N',
  'crdt_able_yn': 'Y',
  'grmn_rate_cls_code': '60',
  'elw_pblc_yn': 'Y',
  'stck_prpr': '286000',
  'prdy_vrss': '-28500',
  'prdy_vrss_sign': '5',
  'prdy_ctrt': '-9.06',
  'acml_tr_pbmn': '11003288574000',
  'acml_vol': '37658279',
  'prdy_vrss_vol_rate': '150.82',
  'stck_oprc': '290000',
  'stck_hgpr': '304000',
  'stck_lwpr': '281500',
  'stck_mxpr': '408500',
  'stck_llam': '220500',
  'stck_sdpr': '314500',
  'wghn_avrg_stck_prc': '292190.32',
  'hts_frgn_ehrt': '46.88',
  'frgn_ntby_qty': '0',
  'pgtr_ntby_qty': '-4368231',
  'pvt_scnd_dmrs_prc': '349166',
  'pvt_frst_dmrs_prc': '331832',
  'pvt_pont_val': '321666',
  'pvt_frst_dmsp_prc': '304332',
  'pvt_scnd_dmsp_prc': '294166',
  'dmrs_val': '326750',
  'dmsp_val': '299250',
  'cpfn': '7780',
  'rstc_wdth_prc': '94000',
  'stck_fcam': '100',
  'stck_sspr': '232730',
  'aspr_unit': '500',
  'hts_deal_qty_unit_val': '1',
  'lstn_stcn': '5846278608',
  'hts_avls': '16720357',
  'per': '43.57',
  'pbr': '4.47',
  'stac_month': '12',
  'vol_tnrt': '0.64',
  'eps': '6564.00',
  'bps': '63997.00',
  'd250_hgpr': '374500',
  'd250_hgpr_date': '20260619',
  'd250_hgpr_vrss_prpr_rate': '-23.63',
  'd250_lwpr': '59800',
  'd250_lwpr_date': '20250630',
  'd250_lwpr_vrss_prpr_rate': '378.26',
  'stck_dryy_hgpr': '374500',
  'dryy_hgpr_vrss_prpr_rate': '-23.63',
  'dryy_hgpr_date': '20260619',
  'stck_dryy_lwpr': '120200',
  'dryy_lwpr_vrss_prpr_rate': '137.94',
  'dryy_lwpr_date': '20260102',
  'w52_hgpr': '374500',
  'w52_hgpr_vrss_prpr_ctrt': '-23.63',
  'w52_hgpr_date': '20260619',
  'w52_lwpr': '59800',
  'w52_lwpr_vrss_prpr_ctrt': '378.26',
  'w52_lwpr_date': '20250702',
  'whol_loan_rmnd_rate': '0.42',
  'ssts_yn': 'Y',
  'stck_shrn_iscd': '005930',
  'fcam_cnnm': '100',
  'cpfn_cnnm': '7,780 억',
  'frgn_hldn_qty': '2740723918',
  'vi_cls_code': 'N',
  'ovtm_vi_cls_code': 'N',
  'last_ssts_cntg_qty': '1685073',
  'invt_caful_yn': 'N',
  'mrkt_warn_cls_code': '00',
  'short_over_yn': 'N',
  'sltr_yn': 'N',
  'mang_issu_cls_code': 'N'},
 'rt_cd': '0',
 'msg_cd': 'MCA00000',
 'msg1': '정상처리 되었습니다.'}

In [14]:
data = data['output']
data

{'iscd_stat_cls_code': '55',
 'marg_rate': '60.00',
 'rprs_mrkt_kor_name': 'KOSPI200',
 'bstp_kor_isnm': '전기·전자',
 'temp_stop_yn': 'N',
 'oprc_rang_cont_yn': 'N',
 'clpr_rang_cont_yn': 'N',
 'crdt_able_yn': 'Y',
 'grmn_rate_cls_code': '60',
 'elw_pblc_yn': 'Y',
 'stck_prpr': '286000',
 'prdy_vrss': '-28500',
 'prdy_vrss_sign': '5',
 'prdy_ctrt': '-9.06',
 'acml_tr_pbmn': '11003288574000',
 'acml_vol': '37658279',
 'prdy_vrss_vol_rate': '150.82',
 'stck_oprc': '290000',
 'stck_hgpr': '304000',
 'stck_lwpr': '281500',
 'stck_mxpr': '408500',
 'stck_llam': '220500',
 'stck_sdpr': '314500',
 'wghn_avrg_stck_prc': '292190.32',
 'hts_frgn_ehrt': '46.88',
 'frgn_ntby_qty': '0',
 'pgtr_ntby_qty': '-4368231',
 'pvt_scnd_dmrs_prc': '349166',
 'pvt_frst_dmrs_prc': '331832',
 'pvt_pont_val': '321666',
 'pvt_frst_dmsp_prc': '304332',
 'pvt_scnd_dmsp_prc': '294166',
 'dmrs_val': '326750',
 'dmsp_val': '299250',
 'cpfn': '7780',
 'rstc_wdth_prc': '94000',
 'stck_fcam': '100',
 'stck_sspr': '232730',
 'aspr_unit': '500',
 'hts_deal_qty_unit_val': '1',
 'lstn_stcn': '5846278608',
 'hts_avls': '16720357',
 'per': '43.57',
 'pbr': '4.47',
 'stac_month': '12',
 'vol_tnrt': '0.64',
 'eps': '6564.00',
 'bps': '63997.00',
 'd250_hgpr': '374500',
 'd250_hgpr_date': '20260619',
 'd250_hgpr_vrss_prpr_rate': '-23.63',
 'd250_lwpr': '59800',
 'd250_lwpr_date': '20250630',
 'd250_lwpr_vrss_prpr_rate': '378.26',
 'stck_dryy_hgpr': '374500',
 'dryy_hgpr_vrss_prpr_rate': '-23.63',
 'dryy_hgpr_date': '20260619',
 'stck_dryy_lwpr': '120200',
 'dryy_lwpr_vrss_prpr_rate': '137.94',
 'dryy_lwpr_date': '20260102',
 'w52_hgpr': '374500',
 'w52_hgpr_vrss_prpr_ctrt': '-23.63',
 'w52_hgpr_date': '20260619',
 'w52_lwpr': '59800',
 'w52_lwpr_vrss_prpr_ctrt': '378.26',
 'w52_lwpr_date': '20250702',
 'whol_loan_rmnd_rate': '0.42',
 'ssts_yn': 'Y',
 'stck_shrn_iscd': '005930',
 'fcam_cnnm': '100',
 'cpfn_cnnm': '7,780 억',
 'frgn_hldn_qty': '2740723918',
 'vi_cls_code': 'N',
 'ovtm_vi_cls_code': 'N',
 'last_ssts_cntg_qty': '1685073',
 'invt_caful_yn': 'N',
 'mrkt_warn_cls_code': '00',
 'short_over_yn': 'N',
 'sltr_yn': 'N',
 'mang_issu_cls_code': 'N'}

In [15]:
open = int(data['stck_oprc'])
high = int(data['stck_hgpr'])
low = int(data['stck_lwpr'])
close = int(data['stck_prpr'])
volume = int(data['acml_vol'])

open,high,low,close,volume

(290000, 304000, 281500, 286000, 37658279)

In [16]:
{'open':open,
 'high':high,
 'low':low,
 'close':close,
 'volume':volume}

{'open': 290000,
 'high': 304000,
 'low': 281500,
 'close': 286000,
 'volume': 37658279}

# 과거 주가 데이터 가져오기

In [17]:
api_starttime = '00000101'
api_endtime = '99991231'
api_freq = 'D'
api_adj_price = True

In [18]:
ticker = '005930'

tr_id = 'FHKST03010100'

headers = {"content-type":"application/json",
                "appkey":api_key,
                "appsecret":secret_key,
                "authorization":f"Bearer {access_token}",
                "tr_id":tr_id,
                }

params = {
        "fid_cond_mrkt_div_code":"J",
        "fid_input_iscd": ticker,
        "fid_input_date_1":api_starttime,
        "fid_input_date_2":api_endtime,
        "fid_period_div_code":api_freq,
        "fid_org_adj_prc":0 if api_adj_price else 1,
        }
url = base_url + '/uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice'
response = requests.get(url, headers=headers, params=params)

response

In [19]:
import pandas as pd

pd.DataFrame(response.json()['output2'])

,stck_bsop_date,stck_clpr,stck_oprc,stck_hgpr,stck_lwpr,acml_vol,acml_tr_pbmn,flng_cls_code,prtt_rate,mod_yn,prdy_vrss_sign,prdy_vrss,revl_issu_reas
0,20260702,286000,290000,304000,281500,37658279,11003288574000,00,0.00,N,5,-28500,
1,20260701,314500,334500,339000,311500,24968382,8016067724007,00,0.00,N,5,-19500,
2,20260630,334000,323500,343000,321000,29237216,9724402126750,00,0.00,N,2,11000,
3,20260629,323000,331000,335500,316000,35436521,11470650838416,00,0.00,N,5,-16500,
4,20260626,339500,354000,356500,321500,39735951,13408352495497,00,0.00,N,5,-19000,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,20260209,166400,168600,168700,165000,25098971,4192595399422,00,0.00,N,2,7800,
96,20260206,158600,154100,160300,151600,36358081,5664674804196,00,0.00,N,5,-700,
97,20260205,159300,162000,164000,158500,38435228,6197185062736,00,0.00,N,5,-9800,
98,20260204,169100,163500,169400,163100,29943042,4988144010160,00,0.00,N,2,1600,
99,20260203,167500,157900,167500,157200,36529813,5927187709457,00,0.00,N,2,17100,

# 투자자별 데이터

In [20]:
ticker = '005930'

tr_id = 'FHKST01010900'

headers = {"content-type":"application/json",
                "appkey":api_key,
                "appsecret":secret_key,
                "authorization":f"Bearer {access_token}",
                "tr_id":tr_id,
                }

params = {
        "fid_cond_mrkt_div_code":"J",
        "fid_input_iscd": ticker,
        }
url = base_url + '/uapi/domestic-stock/v1/quotations/inquire-investor'
response = requests.get(url, headers=headers, params=params)

response

In [21]:
investor=pd.DataFrame(response.json()['output'])
investor.head()

,stck_bsop_date,stck_clpr,prdy_vrss,prdy_vrss_sign,prsn_ntby_qty,frgn_ntby_qty,orgn_ntby_qty,prsn_ntby_tr_pbmn,frgn_ntby_tr_pbmn,orgn_ntby_tr_pbmn,...,orgn_shnu_vol,prsn_shnu_tr_pbmn,frgn_shnu_tr_pbmn,orgn_shnu_tr_pbmn,prsn_seln_vol,frgn_seln_vol,orgn_seln_vol,prsn_seln_tr_pbmn,frgn_seln_tr_pbmn,orgn_seln_tr_pbmn
0,20260702,286000,-28500,5,6949608,-5006436,-2165761,2022255,-1471339,-616020,...,12201510,4101745,3192745,3579875,7108290,15963728,14367271,2079490,4664084,4195895
1,20260701,314500,-19500,5,5183205,-3377992,-1855765,1652060,-1082144,-585369,...,9034264,3291629,1757847,2901535,5095191,8830389,10890029,1639569,2839992,3486904
2,20260630,334000,11000,2,-97602,-2627167,2731943,-38274,-868492,909288,...,11658137,2262893,3523004,3881457,6899881,13233452,8926194,2301167,4391497,2972169
3,20260629,323000,-16500,5,9127270,-11904952,2446957,2942094,-3849834,801014,...,13751566,4338060,2557641,4453212,4298162,19787451,11304609,1395966,6407476,3652198
4,20260626,339500,-19000,5,9298204,-5975701,-3593889,3132017,-2014229,-1209422,...,9751337,5628927,4353848,3286054,7418297,18829800,13345226,2496910,6368077,4495476

---
# 2. 내 계좌 정보 가져오기

- 현금 잔고 조회
- 보유 종목 조회

## (1) 현금 잔고 조회

- 계좌 조회이기 때문에, 내 계좌번호 정보를 전달해야 함. account_id 이름으로 등록.
- account_suffix는 XXXXXXXX-01 이렇게, - 다음에 오는 두 자리 숫자. 첫 계좌라면 보통 01

In [22]:
# 내 계좌 정보 준비

account_id = config['hantu']['account_id']
account_id

account_suffix = '01'

In [23]:
# 현금 잔고 조회

tr_id = 'VTTC8434R'

headers = {"content-type":"application/json",
        "appkey":api_key,
        "appsecret":secret_key,
        "authorization":f"Bearer {access_token}",
        "tr_id":tr_id,
        }

params = {
"CANO":account_id,
"ACNT_PRDT_CD": account_suffix,
"AFHR_FLPR_YN": "N",
"OFL_YN": "N",
"INQR_DVSN": "01",
"UNPR_DVSN": "01",
"FUND_STTL_ICLD_YN": "N",
"FNCG_AMT_AUTO_RDPT_YN": "N",
"PRCS_DVSN": "01",
"CTX_AREA_FK100": '',
"CTX_AREA_NK100": ''
}

url = base_url + '/uapi/domestic-stock/v1/trading/inquire-balance'

order_result = requests.get(url, headers=headers, params=params).json()

In [24]:
order_result

{'ctx_area_fk100': '                                                                                                    ',
 'ctx_area_nk100': '                                                                                                    ',
 'output1': [],
 'output2': [{'dnca_tot_amt': '0',
   'nxdy_excc_amt': '0',
   'prvs_rcdl_excc_amt': '0',
   'cma_evlu_amt': '0',
   'bfdy_buy_amt': '0',
   'thdt_buy_amt': '0',
   'nxdy_auto_rdpt_amt': '0',
   'bfdy_sll_amt': '0',
   'thdt_sll_amt': '0',
   'd2_auto_rdpt_amt': '0',
   'bfdy_tlex_amt': '0',
   'thdt_tlex_amt': '0',
   'tot_loan_amt': '0',
   'scts_evlu_amt': '0',
   'tot_evlu_amt': '0',
   'nass_amt': '0',
   'fncg_gld_auto_rdpt_yn': '',
   'pchs_amt_smtl_amt': '0',
   'evlu_amt_smtl_amt': '0',
   'evlu_pfls_smtl_amt': '0',
   'tot_stln_slng_chgs': '0',
   'bfdy_tot_asst_evlu_amt': '0',
   'asst_icdc_amt': '0',
   'asst_icdc_erng_rt': '0.00000000'}],
 'rt_cd': '0',
 'msg_cd': '20310000',
 'msg1': '모의투자 조회가 완료되었습니다.                                                 '}

- order_result에서 내 잔고 조회, 보유 종목 조회 정보가 모두 들어있음

In [25]:
# output2에는 현금/평가금액 관련 정보
order_result = order_result['output2'][0]
order_result

{'dnca_tot_amt': '0',
 'nxdy_excc_amt': '0',
 'prvs_rcdl_excc_amt': '0',
 'cma_evlu_amt': '0',
 'bfdy_buy_amt': '0',
 'thdt_buy_amt': '0',
 'nxdy_auto_rdpt_amt': '0',
 'bfdy_sll_amt': '0',
 'thdt_sll_amt': '0',
 'd2_auto_rdpt_amt': '0',
 'bfdy_tlex_amt': '0',
 'thdt_tlex_amt': '0',
 'tot_loan_amt': '0',
 'scts_evlu_amt': '0',
 'tot_evlu_amt': '0',
 'nass_amt': '0',
 'fncg_gld_auto_rdpt_yn': '',
 'pchs_amt_smtl_amt': '0',
 'evlu_amt_smtl_amt': '0',
 'evlu_pfls_smtl_amt': '0',
 'tot_stln_slng_chgs': '0',
 'bfdy_tot_asst_evlu_amt': '0',
 'asst_icdc_amt': '0',
 'asst_icdc_erng_rt': '0.00000000'}

In [26]:
# 보유 현금 조회
float(order_result['prvs_rcdl_excc_amt'])

0.0

## (2) 보유 종목 리턴

- 보유 종목이 50개 이상일 경우, 한번에 전체 종목이 조회되지 않음(최대 50종목까지)
- 때문에, while 문으로 반복하며 여러번 조회해야 함

In [ ]:
# 보유 종목 불러오기

tr_id = 'VTTC8434R'

headers = {"content-type":"application/json",
        "appkey":api_key,
        "appsecret":secret_key,
        "authorization":f"Bearer {access_token}",
        "tr_id":tr_id,
        }

#보유종목 불러오기 관련 파라미
output1_result = []
cont = True
ctx_area_fk100 = ''
ctx_area_nk100 = ''

# while문을 돌며 cont = False가 될때까지 반복
while cont:
    params = {
        "CANO":account_id,
        "ACNT_PRDT_CD": account_suffix,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "N",
        "INQR_DVSN": "01",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": ctx_area_fk100,
        "CTX_AREA_NK100": ctx_area_nk100
    }

    url = base_url + '/uapi/domestic-stock/v1/trading/inquire-balance'

    order_result = requests.get(url, headers=headers, params=params)

    received_headers = order_result.headers
    contents = order_result.json()

    # 다음 종목 조회를 위한 전달값 준비. 한투 서버는 이 값을 받아 사용자가 어디까지 조회했는지를 알 수 있다.
    # F, M 값이라면 아직 조회하지 않은 데이터가 있다는 의미

    cont = received_headers['tr_cont'] in ['F','M']

    # 다음 데이터를 조회하려면 'N' 값으로 둬야함
    headers['tr_cont'] = 'N'
    ctx_area_fk100 = contents['ctx_area_fk100']
    ctx_area_nk100 = contents['ctx_area_nk100']

    # 조회된 데이터 저장
    output1_result = output1_result + contents['output1']
    #output1_result += contents['output1']

In [ ]:
output1_result

[{'pdno': '069500',
  'prdt_name': 'KODEX 200',
  'trad_dvsn_name': '현금',
  'bfdy_buy_qty': '0',
  'bfdy_sll_qty': '0',
  'thdt_buyqty': '70',
  'thdt_sll_qty': '0',
  'hldg_qty': '70',
  'ord_psbl_qty': '70',
  'pchs_avg_pric': '70938.1420',
  'pchs_amt': '4965670',
  'prpr': '70800',
  'evlu_amt': '4956000',
  'evlu_pfls_amt': '-9670',
  'evlu_pfls_rt': '-0.19',
  'evlu_erng_rt': '-0.19473706',
  'loan_dt': '',
  'loan_amt': '0',
  'stln_slng_chgs': '0',
  'expd_dt': '',
  'fltt_rt': '1.12000000',
  'bfdy_cprs_icdc': '785',
  'item_mgna_rt_name': '50%',
  'grta_rt_name': '',
  'sbst_pric': '0',
  'stck_loan_unpr': '0.0000'},
 {'pdno': '152380',
  'prdt_name': 'KODEX 국채선물10년',
  'trad_dvsn_name': '현금',
  'bfdy_buy_qty': '0',
  'bfdy_sll_qty': '0',
  'thdt_buyqty': '74',
  'thdt_sll_qty': '0',
  'hldg_qty': '74',
  'ord_psbl_qty': '74',
  'pchs_avg_pric': '67121.5540',
  'pchs_amt': '4966995',
  'prpr': '67175',
  'evlu_amt': '4970950',
  'evlu_pfls_amt': '3955',
  'evlu_pfls_rt': '0.08',
  'evlu_erng_rt': '0.07962561',
  'loan_dt': '',
  'loan_amt': '0',
  'stln_slng_chgs': '0',
  'expd_dt': '',
  'fltt_rt': '0.17000000',
  'bfdy_cprs_icdc': '115',
  'item_mgna_rt_name': '50%',
  'grta_rt_name': '',
  'sbst_pric': '0',
  'stck_loan_unpr': '0.0000'}]

In [ ]:
# output 값 확인

import pandas as pd

pd.DataFrame(output1_result)

,pdno,prdt_name,trad_dvsn_name,bfdy_buy_qty,bfdy_sll_qty,thdt_buyqty,thdt_sll_qty,hldg_qty,ord_psbl_qty,pchs_avg_pric,...,loan_dt,loan_amt,stln_slng_chgs,expd_dt,fltt_rt,bfdy_cprs_icdc,item_mgna_rt_name,grta_rt_name,sbst_pric,stck_loan_unpr
0,069500,KODEX 200,현금,0,0,70,0,70,70,70938.1420,...,,0,0,,1.12000000,785,50%,,0,0.0000
1,152380,KODEX 국채선물10년,현금,0,0,74,0,74,74,67121.5540,...,,0,0,,0.17000000,115,50%,,0,0.0000

---
# 3. 매수/매도 주문

- 지정가/시장가 주문

In [ ]:
# 매매 파라미터 설정

ord_dvsn = '00' # 00은 지정가, 01은 시장가
ticker = '005930'
quantity = 2 # 주문수량
price = 140000 # 주문가격

In [ ]:
# 매수주문 구현

tr_id = 'VTTC0012U' # VTTC0011U로 바꾸면 매도주문이 됩니다(모의기준)

headers = {"content-type":"application/json",
        "appkey":api_key,
        "appsecret":secret_key,
        "authorization":f"Bearer {access_token}",
        "tr_id":tr_id,
        }

params = {
        "CANO":account_id,
        "ACNT_PRDT_CD": account_suffix,
        'PDNO':ticker,
        'ORD_DVSN':ord_dvsn,
        'ORD_QTY':str(quantity), # 주문수량/가격은 string 값으로 바꿔서 넣어줍니다
        'ORD_UNPR':str(price)
        }

url = base_url + '/uapi/domestic-stock/v1/trading/order-cash'

order_result = requests.post(url, headers=headers, data=json.dumps(params)) # post 방식은 parameter 입력방식이 다름

- 주문이 제대로 완료됐다면, msg1에 주문 전송 완료 되었습니다. 라는 메세지를 볼 수 있음. rt_cd = 0임으로도 확인 가능
- 만약 주문이 제대로 들어가지 않았다면, rt_cd는 0이 아니고, msg1에 오류 이유가 리턴됨
- output의 ODNO는 내 주문의 주문번호로, 뒤에 배울 주문 취소 기능에 필요한 데이터. 저장해두자.

In [ ]:
# 주문 결과 확인

order_result.json()

{'rt_cd': '0',
 'msg_cd': '40600000',
 'msg1': '모의투자 매수주문이 완료 되었습니다.',
 'output': {'KRX_FWDG_ORD_ORGNO': '00950',
  'ODNO': '0000016099',
  'ORD_TMD': '144159',
  'SOR_ODNO': ''}}

In [ ]:
# 매도주문 구현

tr_id = 'VTTC0011U'

headers = {"content-type":"application/json",
        "appkey":api_key,
        "appsecret":secret_key,
        "authorization":f"Bearer {access_token}",
        "tr_id":tr_id,
        }


params = {
        "CANO":account_id,
        "ACNT_PRDT_CD": account_suffix,
        'PDNO':ticker,
        'ORD_DVSN':ord_dvsn,
        'ORD_QTY':str(quantity), # 주문수량/가격은 string 값으로 바꿔서 넣어줍니다
        'ORD_UNPR':str(price)
        }

url = base_url + '/uapi/domestic-stock/v1/trading/order-cash'

order_result = requests.post(url, headers=headers, data=json.dumps(params)) # post 방식은 parameter 입력방식이 다름

In [ ]:
order_result.json()

{'rt_cd': '1', 'msg_cd': '40240000', 'msg1': '모의투자 잔고내역이 없습니다.'}

# 체결 확인

In [ ]:
# 보유 종목 불러오기

tr_id = 'VTTC8434R'

headers = {"content-type":"application/json",
        "appkey":api_key,
        "appsecret":secret_key,
        "authorization":f"Bearer {access_token}",
        "tr_id":tr_id,
        }

#보유종목 불러오기 관련 파라미
output1_result = []
cont = True
ctx_area_fk100 = ''
ctx_area_nk100 = ''

# while문을 돌며 cont = False가 될때까지 반복
while cont:
    params = {
        "CANO":account_id,
        "ACNT_PRDT_CD": account_suffix,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "N",
        "INQR_DVSN": "01",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": ctx_area_fk100,
        "CTX_AREA_NK100": ctx_area_nk100
    }

    url = base_url + '/uapi/domestic-stock/v1/trading/inquire-balance'

    order_result = requests.get(url, headers=headers, params=params)

    received_headers = order_result.headers
    contents = order_result.json()

    # 다음 종목 조회를 위한 전달값 준비. 한투 서버는 이 값을 받아 사용자가 어디까지 조회했는지를 알 수 있다.
    # F, M 값이라면 아직 조회하지 않은 데이터가 있다는 의미

    cont = received_headers['tr_cont'] in ['F','M']

    # 다음 데이터를 조회하려면 'N' 값으로 둬야함
    headers['tr_cont'] = 'N'
    ctx_area_fk100 = contents['ctx_area_fk100']
    ctx_area_nk100 = contents['ctx_area_nk100']

    # 조회된 데이터 저장
    output1_result = output1_result + contents['output1']
    #output1_result += contents['output1']

In [ ]:
# output 값 확인

import pandas as pd

pd.DataFrame(output1_result)

,pdno,prdt_name,trad_dvsn_name,bfdy_buy_qty,bfdy_sll_qty,thdt_buyqty,thdt_sll_qty,hldg_qty,ord_psbl_qty,pchs_avg_pric,...,loan_dt,loan_amt,stln_slng_chgs,expd_dt,fltt_rt,bfdy_cprs_icdc,item_mgna_rt_name,grta_rt_name,sbst_pric,stck_loan_unpr
0,069500,KODEX 200,현금,0,0,70,0,70,70,70938.1420,...,,0,0,,0.84000000,590,50%,,0,0.0000
1,152380,KODEX 국채선물10년,현금,0,0,74,0,74,74,67121.5540,...,,0,0,,0.22000000,145,50%,,0,0.0000

---
# 4. 주문 취소

In [ ]:
# 주문 취소 기능 구현

oid = '0000016099' # 앞서 넣은 주문의 ODNO를 기록해두고, 이 값을 활용해 주문 취소 가능

tr_id = 'VTTC0013U'
headers = {"content-type":"application/json",
        "appkey":api_key,
        "appsecret":secret_key,
        "authorization":f"Bearer {access_token}",
        "tr_id":tr_id,
        }

params = {
        "CANO":account_id,
        "ACNT_PRDT_CD": account_suffix,
        "KRX_FWDG_ORD_ORGNO":"",
        "RVSE_CNCL_DVSN_CD":'02', # 취소
        "ORGN_ODNO":oid, # 원주문번호
        "ORD_DVSN":'00',
        "ORD_QTY":'0',
        "ORD_UNPR":'0',
        "QTY_ALL_ORD_YN":"Y" # 전량취소
        }
url = base_url + '/uapi/domestic-stock/v1/trading/order-rvsecncl'
order_result = requests.post(url, headers=headers, data=json.dumps(params)) # post 방식은 parameter 입력방식이 다름

- 제대로 취소됐다면 rt_cd = 0, msg1은 주문 전송 완료 되었습니다. 라는 메세지가 리턴됨

In [ ]:
order_result.json()

{'rt_cd': '0',
 'msg_cd': '40630000',
 'msg1': '모의투자 취소주문이 완료 되었습니다.',
 'output': {'KRX_FWDG_ORD_ORGNO': '00950',
  'ODNO': '0000016124',
  'ORD_TMD': '144232',
  'SOR_ODNO': ''}}